services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "1234"
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - dev-network

  redis:
    image: redis:8.4-alpine
    container_name: redis8
    restart: unless-stopped
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev-network

  memgraph:
    image: memgraph/memgraph:3.11.0
    container_name: memgraph
    restart: unless-stopped
    ports:
      - "7867:7687"
      - "7444:7444"
    volumes:
      - memgraph_data:/var/lib/memgraph
      - memgraph_log:/var/log/memgraph
    networks:
      - dev-network

  memgraph-lab:
    image: memgraph/lab:3.11.0
    container_name: memgraph-lab
    restart: unless-stopped
    depends_on:
      - memgraph
    environment:
      QUICK_CONNECT_MG_HOST: memgraph
      QUICK_CONNECT_MG_PORT: 7687
    ports:
      - "3000:3000"
    networks:
      - dev-network

volumes:
  postgres_data:
  redis_data:
  memgraph_data:
  memgraph_log:

networks:
  dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
