# HAND-WRITTEN PLACEHOLDER — unlike the desktop's copy, this was NOT produced by
# nixos-generate-config, because the machine was not available when the host was
# added. It carries the modules a T480s needs to reach its root filesystem, which
# is enough for the configuration to evaluate and build on another machine.
#
# REPLACE IT with the real thing as the first step of the install (see
# docs/install-t480s.md): boot the ISO on the laptop and run
#
#   nixos-generate-config --show-hardware-config > hardware-configuration.nix
#
# then drop the generated `fileSystems` — those come from ./disko.nix — and keep
# everything else it found.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Enough to see the NVMe/SATA root and a USB keyboard in stage 1. The i915
  # module is added by nixos-hardware's Intel GPU module, so it is not repeated.
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # fileSystems and swapDevices are generated by ./disko.nix — do not add them
  # back here.
  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
