# Written by hand, not by nixos-generate-config — the machine was not available
# when this host was added. It was checked against the real thing during the
# install: `nixos-generate-config --show-hardware-config` on the T480s found
# xhci_pci, nvme, usb_storage and sd_mod, all of which are below, plus the same
# kvm-intel and hostPlatform. The extra modules here (ahci, usbhid,
# rtsx_pci_sdmmc) are a superset and cost nothing in the initrd, so the file was
# kept as written rather than replaced with the generated one.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Enough to see the NVMe/SATA root and a USB keyboard in stage 1. The i915
  # module is added by nixos-hardware's Intel GPU module, so it is not repeated.
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # fileSystems and swapDevices are generated by ./disko.nix — do not add them
  # back here.
  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
